### ISSUE TITLE
Macroeconomic Context Debt

### ISSUE THREAD

**Issue by LUGOCA** [LUGOCA/LAC-Chile-Green-Finance#1]
1. Objective: Macroeconomic and Financial context of Chile since 2018-2020 looking to main landmarks 

a) Pre-post First Green Bond 
b) Social Crisis 18-O
c) Pre - Post Seconf Green Bond 
d) COVID  2/3 Marzo 

2. The question for this task is:: The room for debt insurance in Chile at each moment? and the cost determinants at macro and financial level

- debt structure (local and foreign currencies) compared to LAC ( Pacific Alliance)

Potentiak Variables to explain the cost of debt:
a) CDS 5y or 10 y
b) Fiscal Deficit 
c) Current Account deficit 
d) Rate of GDP Growth 
e) Net Debt level over GDP B/Y 
 and others 

    - Review of empirical evidence on cost determinants (Papers, policy papers and Official reports) 
    - 
 
dauz_ucv@hotmail.com Droopbox
Dauz-ve

**Comment by Dauz-ve** [comment]
Got it - let's do this

**Comment by LUGOCA** [comment]
De la presentación ppt 

- Armar base de datos de los gráficos en excel

**Comment by LUGOCA** [comment]
@Dauz-ve  
Por favor, verificar y tener datos de esta noticia 
https://www.elespectador.com/economia/chile-tiene-la-unica-deuda-con-retorno-positivo-de-america-latina-articulo-916340 
 y hacer seguimiento  para tenerlo en el radar

**Comment by Dauz-ve** [comment]
Hello @LUGOCA ,

To keep things in order, I moved our discussion to two separate issues. 

The first one (https://github.com/LUGOCA/LAC-Chile-Green-Finance/issues/2) has all the comments and requests coming from our presentation on Friday. I'll keep you posted on any updates on that front through this new thread.

The second thread (https://github.com/LUGOCA/LAC-Chile-Green-Finance/issues/3) will have all information pertaining to the quantitative study (or studies) that we'll develop for the final report. As we discussed last Friday, the first step is to structure our database to begin the data request. I'm now compiling that spreadsheet and will upload it to this thread ASAP. And I'll also notify of all updates on that front on the newly-established thread.

**Comment by Dauz-ve** [comment]
Also, thanks @LUGOCA for sharing the news piece (https://www.elespectador.com/economia/chile-tiene-la-unica-deuda-con-retorno-positivo-de-america-latina-articulo-916340). 

In addition to having series for interest rates and credit spread per each Latam country, I'll compile a series on total-return indices per each country. We'll greatly benefit from having Bloomberg access here becasue there are built-in indices for each country. I can point out to the relevant functions on Bloomberg to pull the data, but I'd be able to find the series very quickly if given remote access to a terminal. Thanks!

For now, I'll close this issue, but let me know here or via Whatsapp if you feel I left something out.
